name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.9", "3.11"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Ubuntu dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libpulse0 pulseaudio
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install coverage codecov
    - name: Test with coverage + unittest
      run: |
        coverage run --source=pulsectl_asyncio,examples -m unittest
    - name: Report test coverage
      if: ${{ always() }}
      run: |
        coverage xml
        coverage report -m
    - uses: codecov/codecov-action@v2
      if: ${{ always() }}
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

  package:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Create source and wheel dist
      run: |
        python -m build
